### ISSUE TITLE
Layer sharing model issues

### ISSUE THREAD

**Issue by pdh930105** [facebookresearch/MobileLLM#9]
Thank you for sharing the code for this research.

I couldn't find the code and config file related to layer sharing (-LS) in the model implementation section. 

Will this part be updated in the future?

**Comment by Atharva-Phatak** [comment]
@pdh930105 If you investigate the code for LlamaForCausalLM/LlamaModel you will be able find both the code for layer sharing and embedding sharing.

**Comment by pdh930105** [comment]
@Atharva-Phatak thank you for the info!
